@url = https://order-eg-pipeline-func.azurewebsites.net
#@url = http://localhost:7071

### Generate 1 order using query param.
POST {{url}}/api/orders?count=1 HTTP/1.1

### Generate 1 orders using JSON payload.
POST {{url}}/api/orders HTTP/1.1
Content-Type: application/json

{
  "count": 1
}

### Generate 100 orders using query param.
POST {{url}}/api/orders?count=100 HTTP/1.1

### Generate orders error with no count.
POST {{url}}/api/orders HTTP/1.1
Content-Type: application/json

{
  "orders": 0
}

### Get all orders.
GET {{url}}/api/orders HTTP/1.1

### Get a specific order.
GET {{url}}/api/orders/44b27b5d-7116-40a9-9324-025f6ca90e2b HTTP/1.1

### Approve a specific order.


### Delete all orders.
DELETE {{url}}/api/orders HTTP/1.1

### Send event for order payment. (Only works locally)
POST http://localhost:7071/runtime/webhooks/EventGrid?functionName=ProcessOrderPayment HTTP/1.1
Content-Type: application/json
aeg-event-type: Notification

[{
  "topic": "/subscriptions/{{$guid}}/resourceGroups/resource-group-name/providers/Microsoft.EventGrid",
  "subject": "/custom-event",
  "eventType": "CustomEvent",
  "eventTime": "2018-01-23T17:02:19.6069787Z",
  "id": "00000000-a73d-45b6-8e76-000000000000",
  "dataVersion": "1",
  "medataVersion": "1",
  "data": {
    "id": "6abf163b-fa21-4571-8360-b53998583904",
    "firstName": "Lisette",
    "lastName": "Bashirian",
    "address": "025 Rodriguez Station, North Christianview, Lebanon",
    "email": "Lisette_Bashirian@yahoo.com",
    "tax": null,
    "total": null,
    "lineItems": [
      {
        "productName": "Shoes",
        "price": 85.12,
        "quantity": 6
      }
    ],
    "approvals": null,
    "anticipatedDeliveryDate": null,
    "createdTimestamp": "2022-03-10T17:49:45.8572125Z",
    "paidTimestamp": null,
    "shippedTimestamp": null,
    "notifiedTimestamp": null
  }
}]